# >>> Custom Configurations, that make me happy.

# Default apps
$browser = firefox
$editor = nano
$terminal = kitty

# Unbinding
unbind = SUPER, RETURN
unbind = SUPER, K
unbind = SUPER SHIFT, F
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT ALT, B
unbind = SUPER SHIFT, M
unbind = SUPER SHIFT, N
unbind = SUPER SHIFT, T
unbind = SUPER SHIFT, D
unbind = SUPER SHIFT, G
unbind = SUPER SHIFT, O
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, SLASH
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT ALT, A
unbind = SUPER SHIFT, C
unbind = SUPER SHIFT, E
unbind = SUPER SHIFT, Y
unbind = SUPER SHIFT ALT, G
unbind = SUPER SHIFT CTRL, G
unbind = SUPER SHIFT, P,
unbind = SUPER SHIFT, X
unbind = SUPER SHIFT ALT, X

# Bindings
bindd = SUPER, K, Terminal, exec, kitty
bindd = SUPER, F, File manager, exec, nautilus --new-window
bindd = SUPER, B, Browser, exec, firefox
bindd = SUPER, G, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, B, Browser (private), exec, firefox --private
bindd = SUPER, M, Mail, omarchy-launch-webapp "https://mail.google.com"
bindd = SUPER, T, Typora, exec, typora --enable-wayland-ime

# Touchpad settings
input {
  touchpad {
    natural_scroll = true;
  }
}
