font_family MonoLisa Variable
bold_font MonoLisa Variable SemiBold
italic_font MonoLisa Variable Italic
bold_italic_font MonoLisa Variable SemiBold Italic
font_size 9.0

disable_ligatures never

font_features MonoLisaVariable-Regular         +ss03 +ss07 +ss11 +ss12 +ss13 +ss17
font_features MonoLisaVariableRegular-SemiBold +ss03 +ss07 +ss11 +ss12 +ss13 +ss17
font_features MonoLisaVariable-Italic          +ss03 +ss07 +ss11 +ss12 +ss13 +ss17
font_features MonoLisaVariableItalic-SemiBold  +ss03 +ss07 +ss11 +ss12 +ss13 +ss17

macos_option_as_alt yes

tab_bar_edge top
tab_bar_align left
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol *
tab_title_max_length 24

macos_menubar_title_max_length 24

hide_window_decorations yes

editor nano
macos_quit_when_last_window_closed yes

map command+enter no_op
map command+r no_op
map control+shift+left no_op
map control+shift+right no_op

map command+1 goto_tab 1
map command+2 goto_tab 2
map command+3 goto_tab 3
map command+4 goto_tab 4
map command+5 goto_tab 5
map command+6 goto_tab 6
map command+7 goto_tab 7
map command+8 goto_tab 8
map command+9 goto_tab 9


include /opt/dracula-theme/kitty/dracula.conf
